# fly.toml file generated for casper-cgm on 2022-09-29T14:20:35+02:00

app = "casper-cgm"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DISPLAY_UNITS = "mmol"
  ENABLE = "careportal boluscalc rawbg iob cob basal bolus dbsize sage"
  AUTH_DEFAULT_ROLES = "denied"
  BG_HIGH = "12"
  BG_TARGET_TOP = "10"
  BG_TARGET_BOTTOM = "4"
  BG_LOW = "3.9"
  ALARM_URGENT_HIGH = "off"
  ALARM_HIGH = "off"
  ALARM_LOW = "off"
  ALARM_URGENT_LOW = "off"
  ALARM_TIMEAGO_WARN = "off"
  ALARM_TIMEAGO_URGENT = "off"
  DEVICESTATUS_ADVANCED = "on"
  TIME_FORMAT = "24"
  DAY_START = "9"
  DAY_END = "2"
  THEME = "colors"
  SHOW_PLUGINS = "iob cob basal bolus delta timeago upbat direction timeago ar2 dbsize sage"
  DBSIZE_IN_MIB = "true"
  AR2_CONE_FACTOR = "0"
  SHOW_RAWBG = "noise"
  CUSTOM_TITLE = "🐲📊🩸🍬🍰💯"
  SCALE_Y = "linear"
  SAGE_INFO = "288"
  SAGE_WARN = "312"
  SAGE_URGENT = "324"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["node", "lib/server/server.js"]
  entrypoint = []
  exec = []

[processes]
  app = "node lib/server/server.js"

[[services]]
  http_checks = []
  internal_port = 1337
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
